name: SimiSimi deploy CI

on:
  push:
    branches: ["main"]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    env:
      REGISTRY: StoryBook
    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: 'echo "$KEY"'
        shell: bash
        env:
          KEY: ${{secrets.AWS_ACCESS_KEY_ID}}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        run: yarn build-storybook && aws s3 sync storybook-static s3://simisimi/
